### ISSUE TITLE
Contributors discount not working?

### ISSUE THREAD

**Issue by jsjoeio** [gatsbyjs/store.gatsbyjs.org#113] opened 2018-08-09 21:09 UTC
### Description
I contributed 2x to Gatsby and would like to claim my free swag. However, when I sign in with GitHub then continue through Shopify to add coupon and complete purchase, I get the message: 

>Customer information does not meet the requirements for the BUILDWITHGATSBY discount code

###  Screenrecording:
![hw60myyvxz](https://user-images.githubusercontent.com/3806031/43925848-54227fd8-9bdd-11e8-8e1b-2dfb18d72218.gif)

### Other helpful information:
- Yes, I'm using the same email: jjprevite@gmail.com
- I recently changed my GitHub username from @jjprevite to @jsjoeio 
- My first name on GitHub was recently changed from Joe to JavaScript
- No, I haven't used the coupon already :)

**Comment by jlengstorf** [comment] 2018-08-11 02:57
Hey, @jsjoeio — it looks like there's a problem with Shopify's API not updating customer accounts after they've already ordered. I just manually updated your account, so this should work now. Let me know if it doesn't. I'm going to close this issue for now, though. 

Thanks!

**Comment by GregBorrelly** [comment] 2018-11-20 17:37
@jlengstorf  having the same issue

**Comment by jlengstorf** [comment] 2018-11-21 03:33
@GregBorrelly can you email me at jason@gatsbyjs.com to let me know which email you're using? We'll get you sorted out.

Thanks!

**Comment by filips123** [comment] 2018-12-20 19:14
@jlengstorf I have same problem, but I'm getting error code "BUILDWITHGATSBY discount code isn’t available to you right now".

**Comment by jlengstorf** [comment] 2018-12-23 21:53
@filips123 it appears we introduced a regression with https://github.com/gatsbyjs/api.gatsbyjs.org/pull/17 that wasn't setting up the Shopify account properly. This has been patched as of yesterday, but please let us know at team@gatsbyjs.com if you're still unable to claim the discount. Thanks!

**Comment by berkeleycole** [comment] 2019-02-25 20:24
I'm still unable to claim the discount. 

Error: BUILDWITHGATSBY discount code isn’t available to you right now

<img width="505" alt="screen shot 2019-02-25 at 12 24 09 pm" src="https://user-images.githubusercontent.com/10124835/53366384-49a36280-38f8-11e9-95cb-700a2b501ad7.png">

**Comment by jlengstorf** [comment] 2019-02-25 22:47
@berkeleycole the email address at checkout needs to exactly match the email you use for GitHub (we link the email to the discount code). If that doesn’t work, can you please send me an email (jason@gatsbyjs.com) with your GitHub email address so I can figure out what went wrong?

Thanks!

**Comment by ganapativs** [comment] 2019-09-09 06:00
<img width="440" alt="Screenshot 2019-09-09 at 11 11 44 am" src="https://user-images.githubusercontent.com/4010960/64505816-ce812700-d2f2-11e9-9581-02e1bdce2f65.png">

I gave different email(not the primary email in GitHub) to gatsby store while logging in. Now coupon code "BUILDWITHGATSBY" won't work anymore when using either of the emails while check out 😅

@jlengstorf Help? 😬

**Comment by dpdhruv** [comment] 2019-10-08 18:00
Hello there , I'm facing the same issue. Not able to apply the code as it says "The code is not available to you right now". 

Can anyone help me with it? @jlengstorf

**Closed** 2019-10-09 16:43 UTC
