### ISSUE TITLE
No Middle Initial on Checkout Form?

### ISSUE THREAD

**Issue by jjprevite** [gatsbyjs/store.gatsbyjs.org#66] opened 2018-07-06 00:59 UTC
Hi! 👋🏼

I tried to make a purchase on the store. I selected GPay - it selected my credit card. Then I selected "Use a different billing address". In the field, I double-checked and have everything correct, except for the name. On my credit card, it is listed as FirstName MI LastName. However, the form does not have a section for MI and because of this, it threw it an error "There was an error processing your payment. Please try again." 

I could be wrong but am 95% sure this is the issue.
<img width="594" alt="screen shot 2018-07-05 at 5 53 50 pm" src="https://user-images.githubusercontent.com/3806031/42386789-57c95a4c-80f5-11e8-8879-0e4a45c46661.png">

No errors logged to the console.

Happy to test this again later if the form fields change!

**Comment by jjprevite** [comment] 2018-07-08 17:30
After taking a look at how the Gatsby store is built, I realize this is may be an issue with Shopify's SDK and not necessarily Gatsby Store. Going to look at little deeper before closing this issue.

**Comment by jlengstorf** [comment] 2018-07-12 18:30
Hey, @jjprevite! I actually think the problem is that we haven't enabled credit card payments (the store isn't officially open yet).

The store is still in test mode, but doesn't seem to tell anyone that. 😅

I'm going to close this, but we will pay attention once we enable credit card payments.

**Closed by jlengstorf** 2018-07-12 18:30 UTC
