### ISSUE TITLE
Redesign "claim your discount" on the dashboard

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#15] opened 2018-06-20 14:46 UTC
I had to guess that the Dashboard would let me claim my discount code. Wondering how we can improve that without cluttering the UI too much…will let that simmer a little.

**Comment by fk** [comment] 2018-06-28 13:43
You're not alone anymore! ;-)

**Comment by fk** [comment] 2018-06-28 14:00
One approach could be to solve this with a bespoke callout:

**Comment by fk** [comment] 2018-07-02 19:58
Quoting myself from https://github.com/gatsbyjs/store.gatsbyjs.org/issues/22#issuecomment-401915629: 

> Here's a "screen size lowest common denominator" clickable Figma prototype showing
>
> - the log in button with GitHub logo and "Log in with GitHub" text and
> - the callout from #15 (comment) to inform users/contributors about "free swag" and "log in with your Github account":
https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=1%3A2&scaling=min-zoom lets you log in and open the dropdown menu for the logged in user.
>
> The current design also shows a possible option to make the header with navigation, shopping cart and login button/user profile fit on a 320px-wide screen by dropping the links to "Swag Store" and "Dashboard", and by omitting the "Gatsby" wordmark. If we want to keep these around for small devices, I don't see a much better solution than adding a hamburger button to the header (although we could try to overflow-scroll the navigation items a la reactjs.org—we'd have to drop the "Store" and username at least on the very small screens though).
>
> On larger screens we can show the "Gatsby" wordmark and increase font sizes for the button and username: https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=28%3A1&scaling=min-zoom

**Comment by jlengstorf** [comment] 2018-07-13 22:23
Closing as either a duplicate of #85 or something that's already been handled.

**Closed by jlengstorf** 2018-07-13 22:23 UTC
Labels: 🎯 Company, 🎯 DevRel
